version: '3'
services:

  gatk4:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gatk4
    ports: 
      - "8888:8888"
    volumes:
      - ./workspace:/home/jupyter
    command: "jupyter notebook --allow-root --ip 0.0.0.0 --no-browser"
